services:
  jupyterlab:
    image: jiaxingqiu/contrans2023
    env_file:
      - .env
    ports:
      - "8890:8888"
    volumes:
      - ./:/constrans2023
    networks:
      - dbnetwork
  postgres:
    image: jiaxingqiu/contrans2023
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork: